name: Mirror private repository and check commit convention

on:
  push:
    branches:
      - "**"

jobs:
  mirror:
    if: github.repository == 'jeremyarmijo/R-Type'
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository
        run: |
            git clone --mirror https://${{ secrets.TOKEN }}@github.com/jeremyarmijo/R-Type.git
            cd R-Type.git
            git push --mirror https://${{ secrets.TOKEN }}@github.com/EpitechPGE3-2025/G-CPP-500-PAR-5-2-rtype-12.git | echo "Mirror completed"

  check-commit-convention:
    if: github.repository == 'jeremyarmijo/R-Type'
    runs-on: ubuntu-latest
    needs: mirror
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint commit message
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: ".commitlintrc.js"
